### ISSUE TITLE
Incompatibility issue between `AthenaLib` and `AthenaTwitchLib`

### ISSUE THREAD

**Issue by ClasherKasten** [DirectiveAthena/AthenaTwitchBot#38]
The `data` parameter of the `_request` method had before the change a type annotation of `dict | None` which got narrowed/widened to `MutableMapping[str, Any]`. As this gets passed down to the `AthenaLib` requests functions as is, this code is unable to work. 

The following code can be found in `AthenaLib`;
```python
async def _request(
        headers:dict, url:str, data:bytes=None, query_parameters:dict=None,
        *, loop:asyncio.AbstractEventLoop=None, method:str
):
    if loop is None:
        loop = asyncio.get_running_loop()

    # assemble the request
    req = urllib.request.Request(
        f"{url}?{urllib.parse.urlencode(query_parameters)}" if query_parameters is not None or query_parameters else url,
        headers=headers,
        method=method,
    )

    # run the request
    return await loop.run_in_executor(
        executor=None,
        func=lambda: urllib.request.urlopen(req,data=data)
    )
```

Unfortunately every request method uses this helper function to make the requests. But nowhere between passing a `MutableMapping` to the `_request` method in `AthenaTwitchLib` and passing `data` into the `_request` function in `AthenaLib` exists any attempt to transform `data` into bytes. So this will ultimately crash, as `urllib.request.urlopen` only accepts `bytes` as a type and not any type of `Mapping` or `MutableMapping`

**Comment by AnnaSasDev** [comment]
given I'm currently working on a total refactor of the entire library, see #28 , I'm planning on redesigning the whole API system.
Ergo, this does not need fixing, as it is already marked to be thrown out and redesigned
