### ISSUE TITLE
Incomplete and incorrect type annotations

### ISSUE THREAD

**Issue by ClasherKasten** [DirectiveAthena/AthenaTwitchBot#46]
### Complete untyped defs:
- Some functions aren't type annotated at all.
For examples look at section **"Typing in 3.11"**

### Generic `Callable`s especially: 
- makes it pretty hard to know which functions can get passed where as callbacks
Excerpt of all the places where this happens:
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/irc_connection_protocol.py#L43
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/commands.py#L62
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/irc_connection.py#L128
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/tags/_tags.py#L25
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/_logic.py#L19
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/tasks.py#L42

### Incomplete generic types in general:
Excerpt of examples:
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/irc_connection.py#L44
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/tags/tags_clearmsg.py#L29

### Typing in 3.11
- You wanted `Self`, so then use it when you can and when it's useful.
Examples:
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/_logic.py#L35
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/tasks.py#L44
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/commands.py#L64
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/commands_sqlite.py#L73

### Ignorance about typing in general
- things that seem correctly typed, but aren't as the author seem to never have even tried to take a look how to type annotate properly
Examples: 
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/logic/commands.py#L62
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/tags/_tags.py#L63
(`dict[KeyType, ValueType]`)

### Incredibly strict types
- `dict` isn't very useful, as eventually other people want to pass a data structure into the function that acts like a `dict`, but has some more features they need.
For examples look at the section **"Ignorance about typing in general"**
Tip: Use ABCs like `MutableMapping`, `Mapping`, ...

### Type comments
- Who the hell uses type comments anyway?
Excuse me? We have the year 2022.
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/3623036c772c39d197d3f992bc503184613ec1db/src/AthenaTwitchLib/irc/logic/commands_sqlite.py#L109

### Implicit optionals wherever you look
- General cases where it eventually is needed, but is just not type annotated
Example:
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/3623036c772c39d197d3f992bc503184613ec1db/src/AthenaTwitchLib/irc/tags/tags_clearchat.py#L23-L26
- places where a `bool` is expected?
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/a15418e6e2a553871ba9b297a55c95c2be62f4e7/src/AthenaTwitchLib/irc/tags/tags_privmsg.py#L31-L32

### Typos
https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/blob/3623036c772c39d197d3f992bc503184613ec1db/src/AthenaTwitchLib/irc/bot.py#L30-L32

Guess that are pretty much the most common issues in this code. If i notice some else I gonna edit them in :+1:

**Comment by AnnaSasDev** [comment]
> Ignorance about typing in general

> things that seem correctly typed, but aren't as the author seem to never have even tried to take a look how to type annotate properly

> Who the hell uses type comments anyway?
Excuse me? We have the year 2022.

There is no need try and take jabs. 
Like I said in #45 , the project is still in development and isn't expected to be fully completed until a lot more work is done. I appreciate your effort to help point out some inconsistencies with typing, and will take them forward with me.

**Comment by ClasherKasten** [comment]
> Like I said in https://github.com/Athena-Chaos-Driven-Code/AthenaTwitchLib/pull/45 , the project is still in development and isn't expected to be fully completed until a lot more work is done.

Most of these points don't apply only to this project but instead to all Athena Projects. And with you placing particular value on having a typed codebase it seems like a surprise that there are still so many errors that are absolutely unnecessary at this point. (Just a thought-provoking: eventually `mypy` is just superior to `PyCharm` when it comes to type checking as it is a tool that is made for exactly this problem while `PyCharm` is just a bunch of tools put together in a horrible way...)

**Comment by AnnaSasDev** [comment]
Again, there is no need to try and take jabs at my self taught skills. I create these things to learn, that also means mistakes happen and because I have so many projects running at one time it can take some time to resolve them all.

`mypy` is indeed a great type checker, but I don't see the relevance when it comes to comparing it to an IDE like `PyCharm` or any IDE for that manner.  

I think you have made your point clear that you dislike the way I approach projects, and that is perfectly fine. I do not expect you to keep helping on these kinds of projects if you don't want to.
